#
# NOTE: FOR REAL PRODUCTION DO NOT COMMIT SECRETS TO A SOURCE CODE REPOSITORY
#
apiVersion: v1
metadata:
  name: postgres-db-password
data:
  password: {{ .Values.postgresDbPassword }}
kind: Secret
type: Opaque
